export const HOMEPAGE = {
    AVATAR_IMAGE: ".MuiAvatar-img",
    FULL_NAME_SIDERBAR: "[data-test='sidenav-user-full-name']",
    USERNAME_SIDERBAR: "[data-test='sidenav-username']",
    ACCOUNT_BALANCE_SIDERBAR: ":nth-child(1) > .MuiTypography-subtitle2",
    HOME_SIDERBAR_ICON: "[data-test='sidenav-home'] > .MuiListItemIcon-root",
    HOME_SIDERBAR_TEXT: "[data-test='sidenav-home']",
    MY_ACCOUNT_SIDERBAR_ICON: "[data-test='sidenav-user-settings'] > .MuiListItemIcon-root",
    MY_ACCOUNT_SIDERBAR_TEXT: "[data-test='sidenav-user-settings']",
    BANK_ACCOUNTS_SIDERBAR_ICON: "[data-test='sidenav-bankaccounts'] > .MuiListItemIcon-root",
    BANK_ACCOUNTS_SIDERBAR_TEXT: "[data-test='sidenav-bankaccounts']",
    NOTIFICATIONS_SIDERBAR_ICON: "[data-test='sidenav-notifications'] > .MuiListItemIcon-root",
    NOTIFICATIONS_SIDERBAR_TEXT: "[data-test='sidenav-notifications']",
    TOGGLE_SIDERBAR: "[data-test='sidenav-toggle']",
    HEADER_TITLE: "[data-test='app-name-logo']",
    HEADER_NEW_TRANSACTION: "[data-test='nav-top-new-transaction']",
    HEADER_NOTIFICATIONS: "[data-test='nav-top-notifications-link']",
    EVERYONE_TAB: '[data-test="nav-public-tab"]',
    FRIENDS_TAB: '[data-test="nav-contacts-tab"]',
    MINE_TAB: '[data-test="nav-personal-tab"]',
    DATE_PICKER_FILTER: '[data-test="transaction-list-filter-date-range-button"]',
    PRICE_FILTER: '[data-test="transaction-list-filter-amount-range-button"]',
    TITLE_DATE_PICKER: '.Cal__Header__wrapper',
    DAY_1_DATE_PICKER: '.Cal__Weekdays__root > :nth-child(1)',
    DAY_4_DATE_PICKER: '.Cal__Weekdays__root > :nth-child(4)',
    DAY_7_DATE_PICKER: '.Cal__Weekdays__root > :nth-child(7)',
    SELECTED_DATE1_PICKER: '[data-date="2025-08-20"]',
    SELECTED_DATE2_PICKER: '[data-date="2025-08-25"]',
    TEXT_SELECTED_DATE_PICKER: '.Cal__Header__day > :nth-child(1) > .Cal__Header__date',
    VERIFY_SELECTED_DATE_RANGE_PICKER: '[data-test="transaction-list-filter-date-range-button"] > .MuiChip-label',
    CLEAR_BUTTON_DATE_PICKER: '[data-test="transaction-list-filter-date-clear-button'
  };